# Generated by Django 4.1.7 on 2023-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10)),
                ('job_role', models.CharField(max_length=50)),
                ('drive_company_name', models.CharField(max_length=50)),
                ('job_category', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('vacancies', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('venue_details', models.TextField(blank=True, max_length=200, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jobDetails',
                'verbose_name_plural': 'jobDetailss',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
