# Generated by Django 4.1.7 on 2023-03-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobDetailModel',
            new_name='job',
        ),
    ]
