# Generated by Django 4.1.7 on 2023-03-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_jobapplication_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default=('Pending', 'Pending'), max_length=50),
        ),
    ]
